name: Update FedRAMP Docs Daily

on:
  schedule:
    # Runs at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update submodules
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        # Update all submodules to latest
        git submodule update --remote fedramp-docs
        git submodule update --remote fedramp-rfcs
        git submodule update --remote fedramp-roadmap
        
        # Check if there are changes
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected in FedRAMP repositories"
          
          # Add and commit the changes
          git add fedramp-docs fedramp-rfcs fedramp-roadmap
          git commit -m "Update FedRAMP docs, RFCs, and roadmap submodules [$(date +%Y-%m-%d)]"
          
          # Push the changes
          git push origin main
          
          echo "FedRAMP repositories updated successfully"
        else
          echo "No changes in FedRAMP repositories"
        fi